name: eduspark
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Add any packages from pub.dev here. For the UI we built, you need:
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# This is the single, corrected 'flutter' section.
# All flutter-specific configurations go under this one key.
flutter:
  uses-material-design: true

  # Asset declaration for your images
  assets:
    - assets/images/