name: eduspark
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0 # For beautiful UI animations
  lottie: ^3.1.2         # For the splash screen animation

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/EduSpark_Logo.jpg"
